// <auto-generated />
using System;
using Bmerketo_WebApp.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bmerketo_WebApp.Migrations.Data
{
    [DbContext(typeof(DataContext))]
    [Migration("20230524165740_ContactForms")]
    partial class ContactForms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bmerketo_WebApp.Models.Entities.ContactFormEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactForms");
                });

            modelBuilder.Entity("Bmerketo_WebApp.Models.Entities.ProductCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Hem Elektronik"
                        });
                });

            modelBuilder.Entity("Bmerketo_WebApp.Models.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Arbete har aldrig varit snyggare\r\nOavsett om du föredrar en pekskärm eller en traditionell bildskärm kan du välja bland flera skärmalternativ till ThinkPad T14s Gen 2. Vad du än väljer får du smala ramar som ger maximalt skärmutrymme. Välj en FHD-lågenergipanel för maximal batteritid, eller satsa på en FHD-pekskärm med vidvinkelvy. För större detaljskärpa och ljusstyrka och förbluffande korrekta färger kan 4K-bildskärmen fås med Dolby Vision™ IPS HDR.",
                            Price = 1200m,
                            Title = "ThnkPad T14s G2 Core I7 16GB 512GB SSD 14"
                        });
                });

            modelBuilder.Entity("Bmerketo_WebApp.Models.Entities.ProductImageUrlEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrlName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrlName = "https://images.pexels.com/photos/812264/pexels-photo-812264.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
                        });
                });

            modelBuilder.Entity("Bmerketo_WebApp.Models.Entities.ProductRelationshipEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ImageUrlId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImageUrlId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductRelationships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImageUrlId = 1,
                            ProductId = 1,
                            TagId = 1
                        });
                });

            modelBuilder.Entity("Bmerketo_WebApp.Models.Entities.ProductTagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TagName = "new"
                        },
                        new
                        {
                            Id = 2,
                            TagName = "discount"
                        },
                        new
                        {
                            Id = 3,
                            TagName = "popular"
                        },
                        new
                        {
                            Id = 4,
                            TagName = "featured"
                        },
                        new
                        {
                            Id = 5,
                            TagName = "top selling"
                        },
                        new
                        {
                            Id = 6,
                            TagName = "related"
                        });
                });

            modelBuilder.Entity("Bmerketo_WebApp.Models.Entities.ProductRelationshipEntity", b =>
                {
                    b.HasOne("Bmerketo_WebApp.Models.Entities.ProductCategoryEntity", "Category")
                        .WithMany("ProductRelationshipEntities")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bmerketo_WebApp.Models.Entities.ProductImageUrlEntity", "ImageUrl")
                        .WithMany("ProductRelationshipEntities")
                        .HasForeignKey("ImageUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bmerketo_WebApp.Models.Entities.ProductEntity", "Product")
                        .WithMany("ProductRelationshipEntities")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bmerketo_WebApp.Models.Entities.ProductTagEntity", "Tag")
                        .WithMany("ProductRelationshipEntities")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ImageUrl");

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Bmerketo_WebApp.Models.Entities.ProductCategoryEntity", b =>
                {
                    b.Navigation("ProductRelationshipEntities");
                });

            modelBuilder.Entity("Bmerketo_WebApp.Models.Entities.ProductEntity", b =>
                {
                    b.Navigation("ProductRelationshipEntities");
                });

            modelBuilder.Entity("Bmerketo_WebApp.Models.Entities.ProductImageUrlEntity", b =>
                {
                    b.Navigation("ProductRelationshipEntities");
                });

            modelBuilder.Entity("Bmerketo_WebApp.Models.Entities.ProductTagEntity", b =>
                {
                    b.Navigation("ProductRelationshipEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
